name: Thong Bao Thay Doi Code
on:
  push:      # Chạy mỗi khi có code mới được đẩy lên (sau khi bạn sync fork)
  workflow_dispatch: # Cho phép bạn bấm nút chạy thử thủ công

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Gui Mail Custom
        uses: dawidd6/action-send-mail@v3
        with:
          # Thong tin server mail (Vi du: dung Gmail)
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # Noi dung mail ban muon
          subject: "[CANH BAO] DU AN DRONE CO BIEN MOI - KIEM TRA NGAY!"
          body: "Chào bạn, dự án Event-Sharp-NeRF-Drones vừa có cập nhật mới. Hãy vào kiểm tra file xem có ai xóa gì không nhé!"
          to: lethangcdt@gmail.com
          from: Bot GitHub Cua Toi
